# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with: 
        version: 12.x
        
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: install # npm install/ yarn install
    
    - name: Creating build
      run: yarn build
    #- name: installing react-leaflet
    #  run: npm install react-leaflet # npm
    #- name: adding react-leaflet to yarn
    #  run: yarn add react-leaflet # Yarn
    #- name: installing react-leaflet dom
    # run: npm install leaflet react react-dom
    #- name: adding react-leaflet to yarn
    #  run: yarn add leaflet react react-dom      
    - name: installing surge  
      run: npm install -g surge
    
    - name: deploying on surge
      run: surge ./build http://leafmap.surge.sh/ --token ${{secrets.SU_TOKEN}}
